### PR TITLE
1.18 jei gui container handler

### PR DESCRIPTION
**Pull request by gisellevonbingen**
1. Add field JEI_LOADED for hide each Screen's tooltip
1. Split lines Stirling Generators tooltips
1. Add GuiContainerHandler to Stirling Generators

I'll add more machine's changes on this pull request
Belows are example for changes

When JEI not exist

image

JEI loaded

image

### CODE REVIEW

**Comment by gisellevonbingen** [comment]
Changes
1. Crusher
2. Electrolyzer
3. Centrifugal Agitator
4. Compressor

image
image
image
image

**Comment by gisellevonbingen** [comment]
Changes
1. Combustion Generator
2. Aqueoulizer
3. Distillation Unit
4. Gas Furnace

image
image
image
image
image
image

**Comment by gisellevonbingen** [comment]
Changes
1. Electric Furnace
2. Centrifugal Separator
3. Implosion Compressor
4. Blast Furnace

image
image
image
image

**Comment by gisellevonbingen** [comment]
It done.
Show 'Show Recipes' and 'Percent Complete(Burn)' tooltip on gui to whole machines
Without these
1. Tooling Machine : Missing arrow icon 
2. Saw Mill : Missing category
3. Primitive Blast Furnace : Missing category

**Comment by Eelt** [comment]
Looks good, will merge it in!

**Pull request merged**
